# Estatística Aplicada à Computação/Telemática 
# Lista de Exercícios 5

__Aluno:__ Guilherme Santos Silva

In [1]:
import pandas as pd
import numpy as np

__1. Determine se os dados são qualitativos ou quantitativos. Explique seu raciocínio.__

(a) Alturas de balões de ar quente;7

(b) Capacidades de carga de caminhonetes;8

(c) Cores dos olhos de modelos;9

(d) Números de identidade de estudantes;10

(e) Respostas em uma pesquisa de opinião.13

_Respostas:_

__a)__ Quantitativo, pois as alturas dos balões são medidas numéricas.

__b)__ Quantitativo, por capacidade ser medido em números

__c)__ Qualitativo, pelo motivo que as cores dos olhos são atributos de um indíviduo. 

__d)__ Quantitativo, porque as identificações de identidade dos estudantes serem de medidas númericas. 

__e)__ Qualitativo, porque as respostas de pesquisas são atributos.

__2. Na tabela abaixo temos informações sobre o sexo, a matéria predileta (Português, Matemática, História, Geografia ou Ciências) no 2 o grau e a nota (número de questões certas) em um teste de múltipla escolha com 10 questões de matemática, ministrado no primeiro dia de aula dos calouros de Administração de uma universidade (dados fictícios).__

(a) Classifique as variáveis envolvidas;

(b) Construa a tabela de frequências apropriada para cada uma das variáveis qualitativas.

In [26]:
df = {'Sexo':['F','M','F','F','M','M','F','F','F','M','F','M','M','M','M','M','F','F','M','M','F','F','M','M','F','F','M','M','F','F','F','M','M','F','M','M','F','M','F','F','F','M'], 
      'Predileta':['H','M','P','H','C','H','M','P','H','C','P','M','G','G','M','M','P','G','G','P','M','G','H','M','P','G','C','H','M','P','M','G','H','M','P','G','M','P','M','M','P','M'], 
      'Nota':['5','8','8','6','5','6','8','4','2','6','8','2','4','9','7','1','8','5','9','5','8','6','3','5','5','5','7','4','7','7','6','6','9','8','5','6','7','5','5','5','9','8']}

In [27]:
tab = pd.DataFrame(df)
tab

   Sexo Predileta Nota
0     F         H    5
1     M         M    8
2     F         P    8
3     F         H    6
4     M         C    5
5     M         H    6
6     F         M    8
7     F         P    4
8     F         H    2
9     M         C    6
10    F         P    8
11    M         M    2
12    M         G    4
13    M         G    9
14    M         M    7
15    M         M    1
16    F         P    8
17    F         G    5
18    M         G    9
19    M         P    5
20    F         M    8
21    F         G    6
22    M         H    3
23    M         M    5
24    F         P    5
25    F         G    5
26    M         C    7
27    M         H    4
28    F         M    7
29    F         P    7
30    F         M    6
31    M         G    6
32    M         H    9
33    F         M    8
34    M         P    5
35    M         G    6
36    F         M    7
37    M         P    5
38    F         M    5
39    F         M    5
40    F         P    9
41    M         M    8

In [28]:
tab.columns

Index(['Sexo', 'Predileta', 'Nota'], dtype='object')

In [29]:
tab['Sexo'].value_counts(0)

F    21
M    21
Name: Sexo, dtype: int64

In [30]:
tab['Predileta'].value_counts(0)

M    14
P    10
G     8
H     7
C     3
Name: Predileta, dtype: int64

In [31]:
tab['Nota'].value_counts(0)

5    11
8     8
6     7
7     5
9     4
4     3
2     2
1     1
3     1
Name: Nota, dtype: int64

__3. Considere os dados da tabela abaixo, referentes a um levantamento feito por professores
da Universidade Federal de Santa Catarina (UFSC), onde o principal objetivo era avaliar
os efeitos políticos dos programas de alimentação popular. Aqui temos dados referentes a
40 famílias resi- dentes no Conjunto Residencial Monte Verde, considerando as seguintes
variáveis:__

• PAP: variável indicadora de uso de programas de alimentação (1 = Sim; 0 = Não);

• GI: grau de instrução do chefe da casa (1 = nenhum grau oficialmente completo; 2 = primeiro grau completo; 3 = segundo grau completo);

• RES: número de pessoas residentes na casa;

• RENDA: renda familiar mensal, em salários mínimos.

(a) Classifique as variáveis envolvidas;

(b) Construa a tabela de frequências apropriada para cada uma das variáveis qualitativas.

In [32]:
df1 = {'Ident.':['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40'],'PAP':['0','0','1','0','1','1','0','1','1','1','0','1','0','0','0','0','1','0','0','1','1','1','0','0','0','1','1','0','1','0','1','1','1','1','1','1','1','1','1','1'],
       'GI':['3','3','2','2','3','1','3','3','3','2','2','1','2','2','3','2','3','3','3','3','3','3','3','2','2','3','1','3','2','3','3','2','3','1','1','1','3','3','3','3'],
       'RES':['4','4','4','5','4','1','2','3','6','4','6','4','4','6','3','5','3','4','4','4','5','5','5','4','8','4','5','3','4','5','5','2','5','2','6','8','3','5','5','3'],
       'RENDA':['10,3','15,4','9,6','5,5','9,0','2,4','4,1','8,4','10,3','4,6','18,6','7,1','12,9','8,4','19,3','10,4','8,9','12,9','5,1','12,2','5,8','12,9','7,7','1,1','7,5','5,8','7,2','8,6','5,1','2,6','7,7','2,4','4,8','2,1','4,0','12,5','6,8','3,9','9,0','10,9']}

In [33]:
tab1 = pd.DataFrame(df1)
tab1

   Ident. PAP GI RES RENDA
0       1   0  3   4  10,3
1       2   0  3   4  15,4
2       3   1  2   4   9,6
3       4   0  2   5   5,5
4       5   1  3   4   9,0
5       6   1  1   1   2,4
6       7   0  3   2   4,1
7       8   1  3   3   8,4
8       9   1  3   6  10,3
9      10   1  2   4   4,6
10     11   0  2   6  18,6
11     12   1  1   4   7,1
12     13   0  2   4  12,9
13     14   0  2   6   8,4
14     15   0  3   3  19,3
15     16   0  2   5  10,4
16     17   1  3   3   8,9
17     18   0  3   4  12,9
18     19   0  3   4   5,1
19     20   1  3   4  12,2
20     21   1  3   5   5,8
21     22   1  3   5  12,9
22     23   0  3   5   7,7
23     24   0  2   4   1,1
24     25   0  2   8   7,5
25     26   1  3   4   5,8
26     27   1  1   5   7,2
27     28   0  3   3   8,6
28     29   1  2   4   5,1
29     30   0  3   5   2,6
30     31   1  3   5   7,7
31     32   1  2   2   2,4
32     33   1  3   5   4,8
33     34   1  1   2   2,1
34     35   1  1   6   4,0
35     36   1  1   8  12,5
36     37   1  3   3   6,8
37     38   1  3   5   3,9
38     39   1  3   5   9,0
39     40   1  3   3  10,9

In [34]:
tab1.columns

Index(['Ident.', 'PAP', 'GI', 'RES', 'RENDA'], dtype='object')

In [35]:
tab1['PAP'].value_counts(0)

1    24
0    16
Name: PAP, dtype: int64

In [36]:
tab1['GI'].value_counts(0)

3    23
2    11
1     6
Name: GI, dtype: int64

In [37]:
tab1['RES'].value_counts(0)

4    13
5    11
3     6
6     4
2     3
8     2
1     1
Name: RES, dtype: int64

In [38]:
tab1['RENDA'].value_counts(0)

12,9    3
10,3    2
7,7     2
9,0     2
2,4     2
8,4     2
5,1     2
5,8     2
18,6    1
8,9     1
1,1     1
4,0     1
6,8     1
9,6     1
19,3    1
4,8     1
12,2    1
10,4    1
2,1     1
5,5     1
7,2     1
4,1     1
10,9    1
12,5    1
4,6     1
3,9     1
7,1     1
8,6     1
15,4    1
7,5     1
2,6     1
Name: RENDA, dtype: int64